USE [master]
GO

/****** Object:  Database [UnblockMe]    Script Date: 6/30/2021 11:05:49 AM ******/
CREATE DATABASE [UnblockMe]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UnblockMe', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\UnblockMe.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UnblockMe_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\UnblockMe_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UnblockMe].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UnblockMe] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UnblockMe] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UnblockMe] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UnblockMe] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UnblockMe] SET ARITHABORT OFF 
GO

ALTER DATABASE [UnblockMe] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UnblockMe] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UnblockMe] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UnblockMe] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UnblockMe] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UnblockMe] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UnblockMe] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UnblockMe] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UnblockMe] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UnblockMe] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UnblockMe] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UnblockMe] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UnblockMe] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UnblockMe] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UnblockMe] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UnblockMe] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UnblockMe] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UnblockMe] SET RECOVERY FULL 
GO

ALTER DATABASE [UnblockMe] SET  MULTI_USER 
GO

ALTER DATABASE [UnblockMe] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UnblockMe] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UnblockMe] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UnblockMe] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [UnblockMe] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UnblockMe] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [UnblockMe] SET QUERY_STORE = OFF
GO

ALTER DATABASE [UnblockMe] SET  READ_WRITE 
GO


